### ISSUE TITLE
DO server's public key to Github?

### ISSUE THREAD

**Issue by evanbates** [jlengstorf/tutorial-deploy-nodejs-ssl-digitalocean-app#1]
Nice (and quite successful) tutorial. The only thing I needed to do not in the list was add the new server's public key to Github before pulling the app's repo down (maybe there is a way to avoid this though)...

**Comment by jlengstorf** [comment]
Hey, @evanbates — I think this may be due to the URL used to clone, because you _shouldn't_ need to add an SSH key to clone.

On a public repo, it ought to work key-free. Did you use the `git@github.com` URL? Or the `https://github.com/` form?

**Comment by evanbates** [comment]
Thanks for the reply. Yes, I used the clone dropdown on the Github website which gives git@github.com. So it looks like that's SSH vs. your HTTP-protocol instructions. I guess that explains it, next time I'll have to follow directions!

**Comment by jlengstorf** [comment]
Haha, no worries — I never remember which is which, so I typically try one, then try the other if it complains. :)
