### ISSUE TITLE
Getting Welcome to nginx! page instead of the app page.

### ISSUE THREAD

**Issue by jofftiquez** [jlengstorf/tutorial-deploy-nodejs-ssl-digitalocean-app#10]
I followed everything on the instruction and the video as well, and even when I ran `sudo nginx -t` everything is ok and successful, but when I visit the `foo.bar.com` I only get "Welcome to nginx!" page.

Thanks!

P.S. 

I setup an A record with the name `foo.bar.com` and pointed it to the IP on digital ocean. Am using siteground by the way for the hosting.

**Comment by jlengstorf** [comment]
Hey, @jofftiquez, I saw this issue in the comments thread on the video, and it looks like the other dev was able to resolve it by restarting nginx.

If that's not fixing it for you, I'd raise a question on StackOverflow or your preferred dev channel.

Good luck!

**Comment by jofftiquez** [comment]
@jlengstorf Actually it did. Thanks again.
