### ISSUE TITLE
Is there a way to redirect incoming traffic to https without typing https:// ?

### ISSUE THREAD

**Issue by devMattO** [jlengstorf/tutorial-deploy-nodejs-ssl-digitalocean-app#11]
Hey Jason, loved your tutorial it really helped and wanted to start off by saying thank you. Aiside from that, whenever I want to open up one of my node apps that I deployed using your technique, I have to enter the https://example.com instead of just example.com which gives me an error. This is just because I don't want people trying to view my work and then have an error pop up! Any way to make that work? Or just stick to typing in the https:// ?? Thaaaanks.

**Comment by jlengstorf** [comment]
Hey, @devMattO — there's a bit of config in the Nginx step that will redirect all non-HTTPS traffic to the secure URL. Check out this section of the article and compare it to your config to make sure it's working: https://code.lengstorf.com/deploy-nodejs-ssl-digitalocean/#make-sure-all-traffic-is-secure

Thanks!

**Comment by devMattO** [comment]
Hmm, I believe you’re right, this was my first time going through your tutorial and I guess I took the redirect out for some reason…. lol >.< 
Thank you for the speedy response, I really appreciate it!
