### ISSUE TITLE
SSL certificate auto-renewal cron job not functioning

### ISSUE THREAD

**Issue by jackrvaughan** [jlengstorf/tutorial-deploy-nodejs-ssl-digitalocean-app#13]
Following the instructions for setting up auto-renewal of the SSL certificate don't seem to have worked.

I ran `sudo crontab -e` to get into the file and added these lines: 
```
00 1 * * 1 /opt/letsencrypt/certbot-auto renew >> /var/log/letsencrypt-renewal.log
30 1 * * 1 /bin/systemctl reload nginx
```

It seemed that was all that needed to be done for renewal, but it didn't work. My certificate ran out after 90 days w/ no renewal - fortunately was able to renew fairly easily by closing my nginx server `sudo systemctl stop nginx ` and running `./certbot-auto certonly --standalone` again in `/opt/letsencrypt`.

Not sure if there was anything else I had to do or if I missed something from the article. 

Great instructions overall btw, very thorough!

**Comment by jlengstorf** [comment]
Hey, @jackrvaughan — other devs pointed out in the comments on YouTube that I screwed that part up. 😄 

A fix is to update your cron jobs to this:

```text
59 3 1 * * /bin/systemctl stop nginx && /opt/letsencrypt/letsencrypt-auto renew >> /var/log/letsencrypt-renewal.log && /bin/systemctl start nginx
```

This is a one-liner that stops nginx, runs the renewal command, then restarts nginx.

**Comment by jackrvaughan** [comment]
Awesome, thanks @jlengstorf!
