### ISSUE TITLE
Explicitly mention HTTP2, ipV6, and $http_host settings 

### ISSUE THREAD

**Issue by dgolant** [jlengstorf/tutorial-deploy-nodejs-ssl-digitalocean-app#14]
I had to change the HTTP2 setting, ipV6, and `proxy_set_header Host $http_host;` lines in my nginx config in order to get my own app running after following your guide. Not sure if it's app-specific but I think it's worth calling out explicitly, especially since HTTP2 and IPV6 are by no means default. the proxy_set_header line makes my app fail to load (too many redirs) when it's enabled too, not sure why but worth mentioning.

**Comment by jlengstorf** [comment]
Thanks for this, @blackbetty — HTTP2 is outside the scope of this tutorial, but if you wanted to add a follow-up post that details how you got it working, I'd be happy to add a "further reading" section to link to it.
