### ISSUE TITLE
SSL Auto Renew Error

### ISSUE THREAD

**Issue by kingarawana** [jlengstorf/tutorial-deploy-nodejs-ssl-digitalocean-app#16]
SSL auto renew seems to fail if nginx is running.

I currently have to 1. shut down nginx, 2. run /opt/letsencrypt/certbot-auto renew, 3, start nginx.

Is there a way to get auto renewal to work without having to shut down nginx first?

Here's the error I get when I try to renew without shutting nginx down first.
`
/opt/letsencrypt/certbot-auto renew
Requesting to rerun /opt/letsencrypt/certbot-auto with root privileges...
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/api.mydomain.com.conf
-------------------------------------------------------------------------------
Cert is due for renewal, auto-renewing...
Plugins selected: Authenticator standalone, Installer None
Renewing an existing certificate
Performing the following challenges:
tls-sni-01 challenge for api.mydomain.com
Cleaning up challenges
Attempting to renew cert (api.mydomain.com) from /etc/letsencrypt/renewal/api.mydomain.com.conf produced an unexpected error: Problem binding to port 443: Could not bind to IPv4 or IPv6.. Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/api.mydomain.com/fullchain.pem (failure)

-------------------------------------------------------------------------------

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/api.mydomain.com/fullchain.pem (failure)
-------------------------------------------------------------------------------
1 renew failure(s), 0 parse failure(s)
`

**Comment by jlengstorf** [comment]
There was an error in my cron setup, unfortunately. [This comment](https://www.youtube.com/watch?v=kR06NoSzAXY&lc=UgiSdlMVnDNLxngCoAEC.8PZTeJzKUKH8QqxaBUqcP7) has a fix:

```bash
59 3 1 * * /bin/systemctl stop nginx && /opt/letsencrypt/letsencrypt-auto renew >> /var/log/letsencrypt-reneval.log && /bin/systemctl start nginx
```

**Comment by kingarawana** [comment]
Thanks Jason. Your tutorial was great by the way. I really appreciate it.
