### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by ghost** [jlengstorf/tutorial-deploy-nodejs-ssl-digitalocean-app#17]
After following the instructions I am getting a 502 bad gateway error.

I checked my PM2 logs and I am getting:
`Error: listen EADDRINUSE : : : 80`

So I ran:
`sudo lsof -iTCP -sTCP:LISTEN -P`

And got the following:
```
COMMAND   PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
sshd     1807     root    3u  IPv4  18313      0t0  TCP *:22 (LISTEN)
sshd     1807     root    4u  IPv6  18315      0t0  TCP *:22 (LISTEN)
mongod  13966  mongodb    7u  IPv4  38199      0t0  TCP localhost:27017 (LISTEN)
nginx   19142     root    6u  IPv4 397162      0t0  TCP *:80 (LISTEN)
nginx   19142     root    7u  IPv6 397163      0t0  TCP *:80 (LISTEN)
nginx   19142     root    8u  IPv4 397164      0t0  TCP *:443 (LISTEN)
nginx   19142     root    9u  IPv6 397165      0t0  TCP *:443 (LISTEN)
nginx   19143 www-data    6u  IPv4 397162      0t0  TCP *:80 (LISTEN)
nginx   19143 www-data    7u  IPv6 397163      0t0  TCP *:80 (LISTEN)
nginx   19143 www-data    8u  IPv4 397164      0t0  TCP *:443 (LISTEN)
nginx   19143 www-data    9u  IPv6 397165      0t0  TCP *:443 (LISTEN)
```

Nothing is running on port 80. Not sure what to do at this point. Any help is appreciated.

**Comment by ghost** [comment]
Solved.. but will leave up for anyone else experiencing this issue. 

My app.js was running on port 80. I changed it to run on port 5000 and the issue was fixed.

**Comment by cpbennett4** [comment]
I'm also getting a 502 error.

I checked my error-log by running 'pm2 show server' while SSHed into my droplet.  I then used 'sudo nano <path to error log path>' and the file is empty.  I understand this to mean that there have been no errors like the one you had.  Please correct me if I'm wrong.

When I run 'sudo nano <path to out log path>' i see that my server is running on port 3500 (as expected).  I'm not sure why I'm having this problem and would very much appreciate any help.
