### ISSUE TITLE
Creating backup default.bak caused an issue

### ISSUE THREAD

**Issue by gkiely** [jlengstorf/tutorial-deploy-nodejs-ssl-digitalocean-app#2]
Creating a backup with this code.
`sudo cp /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default.bak`

Led to the following issue later on:
<img width="687" alt="screen shot 2016-10-24 at 10 36 22 pm" src="https://cloud.githubusercontent.com/assets/1948935/19644290/a3212162-9a3a-11e6-99c9-6a36589fef19.png">

**Comment by gkiely** [comment]
Simple rm -f default.bak fixed it, but just making a note.

**Comment by jlengstorf** [comment]
Ah, that's annoying. I didn't realize it recognized `.bak` files in the tests. Thanks for sharing!

**Comment by gkiely** [comment]
No worries, thanks for the great tutorial.

**Comment by jlengstorf** [comment]
I'm glad you liked it! I added a note in the tutorial referencing this issue in case anyone else makes a backup. That's about as much as I can do, so I'm going to close this one. Thanks again!
