### ISSUE TITLE
need help related to SSL installation

### ISSUE THREAD

**Issue by michaelstws** [jlengstorf/tutorial-deploy-nodejs-ssl-digitalocean-app#20]
Your tutorials is very easy to understand. I have followed all steps defined by you. 

I have only one confusion related to SSL installation. I didn't purchase any domain right now. I am using IP address to access the application. Now my question is:

While installing SSL. you have used **app.example.com** many places like in Site configuration. Can I user IP address instead of app.example.com.  Or do I need to follow other way to implement SSL

waiting for your reply.

Thanks

**Comment by jlengstorf** [comment]
Hey, @michaelstws — I'm not actually sure about that. I'd raise this question on the Let’s Encrypt support channel and see if you can find an answer there.

Good luck!
