### ISSUE TITLE
resturl is not working after configuring

### ISSUE THREAD

**Issue by sgotur** [jlengstorf/tutorial-deploy-nodejs-ssl-digitalocean-app#22]
First of all thanks for the excellent step by step article. I used letsencrypt steps to set my restapi to use https
I followed all the steps and only place I see an issue was during the configuration section to use SSL
ssl_certificate /etc/letsencrypt/live/app.example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/app.example.com/privkey.pem;
the path was throwing error and I found my cert is installed under /opt/letsencrypt/letsencrypt-auto-source/tests/certs/localhost/  so I changed the config like below
# Use the Let’s Encrypt certificates
    ssl_certificate /opt/letsencrypt/letsencrypt-auto-source/tests/certs/localhost/server.pem;
    ssl_certificate_key /opt/letsencrypt/letsencrypt-auto-source/tests/certs/localhost/privkey.pem;

after I restart nginx and my PM2, the api is not working (tried via postman)

how do I debug the issue?  I'm new to nginx

**Comment by jlengstorf** [comment]
Hey, @sgotur — so sorry I missed this.

For specific setup troubles, I'd recommend reaching out to the NGINX community. I'm not the best resource for NGINX bugs, and (as evidenced by the delayed response here) you'll get a _much_ faster response from the broader community than from me.

Good luck!
