### ISSUE TITLE
AUTO-RENEWAL for the SSL Certificate issue

### ISSUE THREAD

**Issue by MalekBouba** [jlengstorf/tutorial-deploy-nodejs-ssl-digitalocean-app#25]
Thank you for the great tutorial, it does help us really well.

But,
While **SSL renewal** script use the **port 80**.
I am afraid you forgot a little detail for user whose has that port already taken by **NGINX** or one of their hosted apps. 

It returns:

```
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/mydomain.com/fullchain.pem (failure)
```

I think replacing the old crontab script by those lines are adequate to help fix the given situation.

```
00 1 * * 1 /opt/systemctl stop nginx
01 1 * * 1 /opt/letsencrypt/certbot-auto renew >> /var/log/letsencrypt-renewal.log
02 1 * * 1 /bin/systemctl start nginx
```

Of course we need the minimum server down delay, so i choose to change the schedule params. I guess one minutes should by sufficient to the complete the operation.

Could anyone please confirm this fix, and merge it in the tutorial.
Thanks.

**Comment by jlengstorf** [comment]
@MalekBouba This tutorial is a little out-of-date these days, so there's actually an automated fix for this in the latest editions of Let‘s Encrypt: https://certbot.eff.org/lets-encrypt/ubuntuxenial-nginx

The solution you posted should work just fine, I think, but probably the best way to _really_ fix the problem would be to bump to the latest certbot setup.

I'm going to close this for now, but if anyone wants to submit changes to the tutorial, PRs are very welcome!

**Comment by M-Abozaid** [comment]
@MalekBouba  
I used --nginx it fixes the issue for me 
```00 1 * * 1 /opt/letsencrypt/certbot-auto renew --nginx >> /var/log/letsencrypt-renewal.log```
