### ISSUE TITLE
letsencrypt  auto-renewing

### ISSUE THREAD

**Issue by midesweb** [jlengstorf/tutorial-deploy-nodejs-ssl-digitalocean-app#3]
Hi,

I tried to run letsencrypt renewal process. But i got the error:

> Port 443 is already in use by another process.

Then I stoped nginx, ran letsencrypt renewal process again, and started nginx again.

What do you think will be the better option to make the cron task to automate the proccess every 90 days?
thanks

**Comment by jlengstorf** [comment]
Hey, @midesweb — I'm not sure what the best approach is here. I think this may be a better question for https://community.letsencrypt.org/

I'm going to close this because I don't feel confident I can give a thorough enough answer to this question.

**Comment by barbalex** [comment]
I ran into the same problem and have no solution yet. But I do feel that this should be mentioned in the tutorial. Because it is not obvious to you that auto renewing fails. What saved me were the emails from letsencrypt.com.
