### ISSUE TITLE
Support for www

### ISSUE THREAD

**Issue by fartbagxp** [jlengstorf/tutorial-deploy-nodejs-ssl-digitalocean-app#4]
I followed the guide and everything works great, except for one little issue below.

I tried everything to get `www` like `www.mydomain.com` to work with the certificate but everything I did would cause the certificate to bounce.

The tutorial should include two things that should be optional for people.

1) In their domain registrar (cloudflare, namecheap, godaddy, etc), 
Under DNS records, add two A records.
- (Type) `A Record`, (Host) `@`, (Value) `<Droplet IP address>`
- (Type) `A Record`, (Host) `www`, (Value) `<Droplet IP address>`  -> Optional

2) When generating the LetsEncrypt certificate using the command `./letsencrypt-auto certonly --standalone`, you can specify a subdomain for `www` as well.

- Original: `./letsencrypt-auto certonly --standalone`
- Optional: `./letsencrypt-auto certonly --standalone -d www.app.example.com -d app.example.com`

The alternative way above is how I certificate to work with both `www.mydomain.com` and `mydomain.com`.

Note that the certificate generated will be placed in whatever the first domain appears first.
It will generate one certificate.

Thanks for the guide. I had this saved for months, and finally had time to try it out.

**Comment by jlengstorf** [comment]
This is great — thanks for adding this! I'll add a reference to this issue in the article for people who want to support multiple subdomains.
