### ISSUE TITLE
apache

### ISSUE THREAD

**Issue by wondersoftheworld** [jlengstorf/tutorial-deploy-nodejs-ssl-digitalocean-app#6]
hello, thanks for this awesome tutorial.
i am on an apache LAMP server. how can i adopt this tutorial for my setup, especially regarding the ssl part? thanks.

**Comment by jlengstorf** [comment]
Hey, @wondersoftheworld, thanks for reading! I don't think anything changes for the SSL part. The only thing that would change is all the Nginx stuff would swap out for Apache configuration. It looks like DigitalOcean has a write up on [securing Apache with Let’s Encrypt](https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-16-04), so I’d start there.

Good luck!
