### ISSUE TITLE
Permission denied after changing sshd_config settings

### ISSUE THREAD

**Issue by joshdcopeland** [jlengstorf/tutorial-deploy-nodejs-ssl-digitalocean-app#7]
I cant get in as root or my user name now. I'm on a windows machine and I was using git bash

**Comment by joshdcopeland** [comment]
![sshcapture](https://cloud.githubusercontent.com/assets/12787090/21071318/6f71de3c-be62-11e6-8ab6-fbbddcab4a50.JPG)

**Comment by jlengstorf** [comment]
@photoguy1278 Was this an issue with the tutorial, or was it a config typo of some sort?

**Comment by joshdcopeland** [comment]
Hey Jason, first, thank you for doing this. I did make progress after feeling stumped on the above issue but after completing all the steps I am getting a "Welcome to nginx!" message instead of my Node app output. I'm wondering if you have seen this before?

**Comment by joshdcopeland** [comment]
I have a feeling the issue might be in the sites-enabled/default file: 

# HTTP - rdirect all traffic to HTTPS              
server {                                           
        listen 80;                                 
        listen [::]:80 default_server ipv6only=on; 
        return 301 https://$host$request_uri;      
}                                                  
                                                   
# HTTPS - proxy all requests to the Node app       
server {                                           
        # Enable HTTP/2                            
        listen 443 ssl http2;                      
        listen [::]:443 ssl http2;                 
        server_name localberniecrats.com;          
                                                   
        # Use the Let's Encrypt certificates
server {
        # Enable HTTP/2
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        server_name localberniecrats.com;

        # Use the Let's Encrypt certificates
        ssl_certificate /etc/letsencrypt/live/localberniecrats.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/localberniecrats.com/privkey.pem;

        # Include the SSL configuration from cipherli.st
        include snippets/ssl-params.conf;

        location /{
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
                proxy_set_header X-NginX-Proxy true;
                proxy_pass http://localhost:3000/;
                proxy_ssl_session_reuse off;
                proxy_set_header Host $http_host;
                proxy_cache_bypass $http_upgrade;
                proxy_redirect off;
        }
}

**Comment by joshdcopeland** [comment]
I am getting expected application output when I am ssh-ed into the server and run curl http://localberniecrats.com:3000. Its just not working from my browser

**Comment by joshdcopeland** [comment]
OH!! I just needed to restart the server from with  sudo service nginx restart. It works now! Thank you !!!

**Comment by jlengstorf** [comment]
Awesome, glad you got it worked out!

**Comment by harrythree** [comment]
@photoguy1278 I was just seeing the Nginx default page after going through all of the steps on the Youtube video and the blog post. But after doing `sudo service nginx restart` like you mentioned everything worked as expected. Thanks!

@jlengstorf Thanks a ton for such a great tutorial! I loved the video and then having the blog post for reference!
