### ISSUE TITLE
Support mydomain.com and www.mydomain.com in same certificate

### ISSUE THREAD

**Issue by sandorTuranszky** [jlengstorf/tutorial-deploy-nodejs-ssl-digitalocean-app#8]
Would be useful to add info on how SAN is used to create one secrtificate for www and non www version of a domain

**Comment by Lewis65** [comment]
Agreed, I missed the reference to adding both names in the LetsEncrypt wizard and had a bit of trouble straightening out why. Making it explicit in the tutorial would be super!

**Comment by jlengstorf** [comment]
That's a great point. I just updated the tutorial with a note: https://code.lengstorf.com/deploy-nodejs-ssl-digitalocean/#generate-the-ssl-certificate
