### ISSUE TITLE
letsencrypt-auto has been deprecated

### ISSUE THREAD

**Issue by sandorTuranszky** [jlengstorf/tutorial-deploy-nodejs-ssl-digitalocean-app#9]
Just came across that `certbot-auto` is the new official command, `letsencrypt-auto` has been deprecated.

Until May 2016, Certbot was named simply letsencrypt or letsencrypt-auto, depending on install method. Instructions on the Internet, and some pieces of the software, may still refer to this older name.

[Source](http://letsencrypt.readthedocs.io/en/latest/intro.html?highlight=letsencrypt-auto)

**Comment by jlengstorf** [comment]
@sandorTuranszky Thanks for this — any interest in submitting a PR to update the article instructions? https://github.com/jlengstorf/code.lengstorf.com/blob/master/content/blog/deploy-ssl-node-to-digitalocean.md

**Comment by jlengstorf** [comment]
This is now fixed. Thanks, @barbalex!
